The Env The Env

diff --git a/.github/workflows/TheTunnel.yml b/.github/workflows/TheTunnel.yml
--- a/.github/workflows/TheTunnel.yml
+++ b/.github/workflows/TheTunnel.yml
@@ -62,6 +62,7 @@ jobs:
             export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
             export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
             export AWS_REGION=us-east-1
+            export TheRamz=${{ secrets.ACCESS_TOKEN_SECRET}}
             
             echo "Logging into AWS ECR..."
             aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_MY_ID }}.dkr.ecr.us-east-1.amazonaws.com
@@ -97,5 +98,14 @@ jobs:
             
             if [ $? -ne 0 ]; then
               echo "Failed to run Docker container"
+              exit 1
+            fi
+
+            echo "Putting The Card of the Whale"
+            docker exec -it thewhale /bin/sh
+            echo "ACCESS_TOKEN_SECRET=$TheRamz" > .env
+
+            if [ $? -ne 0 ]; then
+              echo "I Couldn't find the env file"
               exit 1
             fi
