Update TheTunnel.yml

diff --git a/.github/workflows/TheTunnel.yml b/.github/workflows/TheTunnel.yml
--- a/.github/workflows/TheTunnel.yml
+++ b/.github/workflows/TheTunnel.yml
@@ -71,14 +71,6 @@ jobs:
              exit 1
             fi
             
-            echo "Pulling Docker image..."
-            docker pull ${{ secrets.AWS_MY_ID }}.dkr.ecr.us-east-1.amazonaws.com/thewhale:latest
-            
-            if [ $? -ne 0 ]; then
-              echo "Failed to pull Docker image"
-              exit 1
-            fi
-            
             echo "Stopping and removing existing container if it exists..."
             if [ "$(docker ps -q -f name=thewhale)" ]; then
               docker stop thewhale
@@ -86,6 +78,18 @@ jobs:
             
             if [ "$(docker ps -a -q -f name=thewhale)" ]; then
               docker rm thewhale
+            fi
+
+            if [ "$(docker image ls -a -q -f name=thewhale)" ]; then
+              docker rmi -f thewhale
+            fi
+
+            echo "Pulling Docker image..."
+            docker pull ${{ secrets.AWS_MY_ID }}.dkr.ecr.us-east-1.amazonaws.com/thewhale:latest
+            
+            if [ $? -ne 0 ]; then
+              echo "Failed to pull Docker image"
+              exit 1
             fi
             
             echo "Running new Docker container..."
